name: Bug Report
description: File a bug report through a simplified form
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the form below to describe the issue.
  - type: input
    id: minecraft_version
    attributes:
      label: Minecraft version
      placeholder: |
        Example: 1.20.1
    validations:
      required: true
  - type: input
    id: td_version
    attributes:
      label: Tweaks Delight version
      placeholder: |
        Example: 26.04.07+26.1-fabric
    validations:
      required: true
  - type: dropdown
    id: mod_loader
    attributes:
      label: Mod loader
      options:
        - Forge
        - Fabric
        - NeoForge
        - Quilt
    validations:
      required: true
  - type: input
    id: fd_version
    attributes:
      label: Farmer's Delight version
      placeholder: |
        Example: 26.1-3.5.2
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Explain what is happening.
      placeholder: |
        Example: When I join a world and I right click a certain block, the game crashes immediately.
    validations:
      required: true
  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to reproduce
      description: How can I make this happen again?
      placeholder: |
        1. Place block.
        2. Attempt to right click the block.
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Upload logs to https://mclo.gs/ and paste the link here.
